// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: protobuf/kvstore/options.proto

package kvstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVStoreKeyOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Mode:
	//
	//	*KVStoreKeyOptions_StaticKey
	//	*KVStoreKeyOptions_DynamicKey
	Mode isKVStoreKeyOptions_Mode `protobuf_oneof:"mode"`
}

func (x *KVStoreKeyOptions) Reset() {
	*x = KVStoreKeyOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreKeyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreKeyOptions) ProtoMessage() {}

func (x *KVStoreKeyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreKeyOptions.ProtoReflect.Descriptor instead.
func (*KVStoreKeyOptions) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{0}
}

func (x *KVStoreKeyOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *KVStoreKeyOptions) GetMode() isKVStoreKeyOptions_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *KVStoreKeyOptions) GetStaticKey() *KVStoreKeyOptions_StaticKeyMode {
	if x, ok := x.GetMode().(*KVStoreKeyOptions_StaticKey); ok {
		return x.StaticKey
	}
	return nil
}

func (x *KVStoreKeyOptions) GetDynamicKey() *KVStoreKeyOptions_DynamicKeyMode {
	if x, ok := x.GetMode().(*KVStoreKeyOptions_DynamicKey); ok {
		return x.DynamicKey
	}
	return nil
}

type isKVStoreKeyOptions_Mode interface {
	isKVStoreKeyOptions_Mode()
}

type KVStoreKeyOptions_StaticKey struct {
	StaticKey *KVStoreKeyOptions_StaticKeyMode `protobuf:"bytes,2,opt,name=static_key,json=staticKey,proto3,oneof"`
}

type KVStoreKeyOptions_DynamicKey struct {
	DynamicKey *KVStoreKeyOptions_DynamicKeyMode `protobuf:"bytes,3,opt,name=dynamic_key,json=dynamicKey,proto3,oneof"`
}

func (*KVStoreKeyOptions_StaticKey) isKVStoreKeyOptions_Mode() {}

func (*KVStoreKeyOptions_DynamicKey) isKVStoreKeyOptions_Mode() {}

type KVStoreValueOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Mode:
	//
	//	*KVStoreValueOptions_General
	//	*KVStoreValueOptions_Numeral
	Mode isKVStoreValueOptions_Mode `protobuf_oneof:"mode"`
}

func (x *KVStoreValueOptions) Reset() {
	*x = KVStoreValueOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreValueOptions) ProtoMessage() {}

func (x *KVStoreValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreValueOptions.ProtoReflect.Descriptor instead.
func (*KVStoreValueOptions) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{1}
}

func (x *KVStoreValueOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *KVStoreValueOptions) GetMode() isKVStoreValueOptions_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *KVStoreValueOptions) GetGeneral() *KVStoreValueOptions_GeneralValueMode {
	if x, ok := x.GetMode().(*KVStoreValueOptions_General); ok {
		return x.General
	}
	return nil
}

func (x *KVStoreValueOptions) GetNumeral() *KVStoreValueOptions_NumeralValueMode {
	if x, ok := x.GetMode().(*KVStoreValueOptions_Numeral); ok {
		return x.Numeral
	}
	return nil
}

type isKVStoreValueOptions_Mode interface {
	isKVStoreValueOptions_Mode()
}

type KVStoreValueOptions_General struct {
	General *KVStoreValueOptions_GeneralValueMode `protobuf:"bytes,2,opt,name=general,proto3,oneof"`
}

type KVStoreValueOptions_Numeral struct {
	Numeral *KVStoreValueOptions_NumeralValueMode `protobuf:"bytes,3,opt,name=numeral,proto3,oneof"`
}

func (*KVStoreValueOptions_General) isKVStoreValueOptions_Mode() {}

func (*KVStoreValueOptions_Numeral) isKVStoreValueOptions_Mode() {}

type KVStoreKeyOptions_StaticKeyMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KVStoreKeyOptions_StaticKeyMode) Reset() {
	*x = KVStoreKeyOptions_StaticKeyMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreKeyOptions_StaticKeyMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreKeyOptions_StaticKeyMode) ProtoMessage() {}

func (x *KVStoreKeyOptions_StaticKeyMode) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreKeyOptions_StaticKeyMode.ProtoReflect.Descriptor instead.
func (*KVStoreKeyOptions_StaticKeyMode) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *KVStoreKeyOptions_StaticKeyMode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVStoreKeyOptions_DynamicKeyMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KVStoreKeyOptions_DynamicKeyMode) Reset() {
	*x = KVStoreKeyOptions_DynamicKeyMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreKeyOptions_DynamicKeyMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreKeyOptions_DynamicKeyMode) ProtoMessage() {}

func (x *KVStoreKeyOptions_DynamicKeyMode) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreKeyOptions_DynamicKeyMode.ProtoReflect.Descriptor instead.
func (*KVStoreKeyOptions_DynamicKeyMode) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{0, 1}
}

type KVStoreValueOptions_GeneralValueMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KVStoreValueOptions_GeneralValueMode) Reset() {
	*x = KVStoreValueOptions_GeneralValueMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreValueOptions_GeneralValueMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreValueOptions_GeneralValueMode) ProtoMessage() {}

func (x *KVStoreValueOptions_GeneralValueMode) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreValueOptions_GeneralValueMode.ProtoReflect.Descriptor instead.
func (*KVStoreValueOptions_GeneralValueMode) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{1, 0}
}

type KVStoreValueOptions_NumeralValueMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KVStoreValueOptions_NumeralValueMode) Reset() {
	*x = KVStoreValueOptions_NumeralValueMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_kvstore_options_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVStoreValueOptions_NumeralValueMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVStoreValueOptions_NumeralValueMode) ProtoMessage() {}

func (x *KVStoreValueOptions_NumeralValueMode) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_kvstore_options_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVStoreValueOptions_NumeralValueMode.ProtoReflect.Descriptor instead.
func (*KVStoreValueOptions_NumeralValueMode) Descriptor() ([]byte, []int) {
	return file_protobuf_kvstore_options_proto_rawDescGZIP(), []int{1, 1}
}

var file_protobuf_kvstore_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*KVStoreKeyOptions)(nil),
		Field:         1000,
		Name:          "kvstore.key_options",
		Tag:           "bytes,1000,opt,name=key_options",
		Filename:      "protobuf/kvstore/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*KVStoreValueOptions)(nil),
		Field:         1001,
		Name:          "kvstore.value_options",
		Tag:           "bytes,1001,opt,name=value_options",
		Filename:      "protobuf/kvstore/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional kvstore.KVStoreKeyOptions key_options = 1000;
	E_KeyOptions = &file_protobuf_kvstore_options_proto_extTypes[0]
	// optional kvstore.KVStoreValueOptions value_options = 1001;
	E_ValueOptions = &file_protobuf_kvstore_options_proto_extTypes[1]
)

var File_protobuf_kvstore_options_proto protoreflect.FileDescriptor

var file_protobuf_kvstore_options_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfd, 0x01, 0x0a, 0x11,
	0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b, 0x76, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4d,
	0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x4c, 0x0a, 0x0b, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4d, 0x6f, 0x64, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x1a, 0x21,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x1a, 0x10, 0x0a, 0x0e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4d,
	0x6f, 0x64, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0xef, 0x01, 0x0a, 0x13,
	0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x12, 0x49, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4b, 0x56,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x1a, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x1a, 0x12, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x3a, 0x5d, 0x0a,
	0x0b, 0x6b, 0x65, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe8, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x4b,
	0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0a, 0x6b, 0x65, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x63, 0x0a, 0x0d,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe9,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x4b, 0x56, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x68, 0x73, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_kvstore_options_proto_rawDescOnce sync.Once
	file_protobuf_kvstore_options_proto_rawDescData = file_protobuf_kvstore_options_proto_rawDesc
)

func file_protobuf_kvstore_options_proto_rawDescGZIP() []byte {
	file_protobuf_kvstore_options_proto_rawDescOnce.Do(func() {
		file_protobuf_kvstore_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_kvstore_options_proto_rawDescData)
	})
	return file_protobuf_kvstore_options_proto_rawDescData
}

var file_protobuf_kvstore_options_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_kvstore_options_proto_goTypes = []interface{}{
	(*KVStoreKeyOptions)(nil),                    // 0: kvstore.KVStoreKeyOptions
	(*KVStoreValueOptions)(nil),                  // 1: kvstore.KVStoreValueOptions
	(*KVStoreKeyOptions_StaticKeyMode)(nil),      // 2: kvstore.KVStoreKeyOptions.StaticKeyMode
	(*KVStoreKeyOptions_DynamicKeyMode)(nil),     // 3: kvstore.KVStoreKeyOptions.DynamicKeyMode
	(*KVStoreValueOptions_GeneralValueMode)(nil), // 4: kvstore.KVStoreValueOptions.GeneralValueMode
	(*KVStoreValueOptions_NumeralValueMode)(nil), // 5: kvstore.KVStoreValueOptions.NumeralValueMode
	(*descriptorpb.MessageOptions)(nil),          // 6: google.protobuf.MessageOptions
}
var file_protobuf_kvstore_options_proto_depIdxs = []int32{
	2, // 0: kvstore.KVStoreKeyOptions.static_key:type_name -> kvstore.KVStoreKeyOptions.StaticKeyMode
	3, // 1: kvstore.KVStoreKeyOptions.dynamic_key:type_name -> kvstore.KVStoreKeyOptions.DynamicKeyMode
	4, // 2: kvstore.KVStoreValueOptions.general:type_name -> kvstore.KVStoreValueOptions.GeneralValueMode
	5, // 3: kvstore.KVStoreValueOptions.numeral:type_name -> kvstore.KVStoreValueOptions.NumeralValueMode
	6, // 4: kvstore.key_options:extendee -> google.protobuf.MessageOptions
	6, // 5: kvstore.value_options:extendee -> google.protobuf.MessageOptions
	0, // 6: kvstore.key_options:type_name -> kvstore.KVStoreKeyOptions
	1, // 7: kvstore.value_options:type_name -> kvstore.KVStoreValueOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	6, // [6:8] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_kvstore_options_proto_init() }
func file_protobuf_kvstore_options_proto_init() {
	if File_protobuf_kvstore_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_kvstore_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreKeyOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_kvstore_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreValueOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_kvstore_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreKeyOptions_StaticKeyMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_kvstore_options_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreKeyOptions_DynamicKeyMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_kvstore_options_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreValueOptions_GeneralValueMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_kvstore_options_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVStoreValueOptions_NumeralValueMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_kvstore_options_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*KVStoreKeyOptions_StaticKey)(nil),
		(*KVStoreKeyOptions_DynamicKey)(nil),
	}
	file_protobuf_kvstore_options_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*KVStoreValueOptions_General)(nil),
		(*KVStoreValueOptions_Numeral)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_kvstore_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_kvstore_options_proto_goTypes,
		DependencyIndexes: file_protobuf_kvstore_options_proto_depIdxs,
		MessageInfos:      file_protobuf_kvstore_options_proto_msgTypes,
		ExtensionInfos:    file_protobuf_kvstore_options_proto_extTypes,
	}.Build()
	File_protobuf_kvstore_options_proto = out.File
	file_protobuf_kvstore_options_proto_rawDesc = nil
	file_protobuf_kvstore_options_proto_goTypes = nil
	file_protobuf_kvstore_options_proto_depIdxs = nil
}
