#!/bin/bash

find . -type f -name "*.go"  -exec grep -qE "// Code generated by (mockery|sqlc|protoc-gen-kvstore).*\. DO NOT EDIT\." {} \; -delete

protoc \
  --go_out=. --go_opt=paths=source_relative \
  protobuf/kvstore/options.proto

protoc \
  --plugin=protoc-gen-kvstore=./protoc-gen-kvstore \
  --go_out=. --go_opt=paths=source_relative \
  --kvstore_out=. --kvstore_opt=paths=source_relative \
  -I. \
  example/example.proto
