// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: examples/balance/balance.proto

package balance

import (
	_ "github.com/ehsundar/kvstore/protobuf/kvstore"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *BalanceKey) Reset() {
	*x = BalanceKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_balance_balance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceKey) ProtoMessage() {}

func (x *BalanceKey) ProtoReflect() protoreflect.Message {
	mi := &file_examples_balance_balance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceKey.ProtoReflect.Descriptor instead.
func (*BalanceKey) Descriptor() ([]byte, []int) {
	return file_examples_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceKey) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BalanceValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance float64 `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *BalanceValue) Reset() {
	*x = BalanceValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_balance_balance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceValue) ProtoMessage() {}

func (x *BalanceValue) ProtoReflect() protoreflect.Message {
	mi := &file_examples_balance_balance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceValue.ProtoReflect.Descriptor instead.
func (*BalanceValue) Descriptor() ([]byte, []int) {
	return file_examples_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceValue) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_examples_balance_balance_proto protoreflect.FileDescriptor

var file_examples_balance_balance_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x15, 0x6b, 0x76, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2d, 0x0a, 0x0a, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x3a, 0x03, 0xc2, 0x3e, 0x00, 0x22,
	0x2f, 0x0a, 0x0c, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x3a, 0x05, 0xca, 0x3e, 0x02, 0x1a, 0x00,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x68, 0x73, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_balance_balance_proto_rawDescOnce sync.Once
	file_examples_balance_balance_proto_rawDescData = file_examples_balance_balance_proto_rawDesc
)

func file_examples_balance_balance_proto_rawDescGZIP() []byte {
	file_examples_balance_balance_proto_rawDescOnce.Do(func() {
		file_examples_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_balance_balance_proto_rawDescData)
	})
	return file_examples_balance_balance_proto_rawDescData
}

var file_examples_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_balance_balance_proto_goTypes = []interface{}{
	(*BalanceKey)(nil),   // 0: balance.BalanceKey
	(*BalanceValue)(nil), // 1: balance.BalanceValue
}
var file_examples_balance_balance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_balance_balance_proto_init() }
func file_examples_balance_balance_proto_init() {
	if File_examples_balance_balance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_balance_balance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_balance_balance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_balance_balance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_balance_balance_proto_goTypes,
		DependencyIndexes: file_examples_balance_balance_proto_depIdxs,
		MessageInfos:      file_examples_balance_balance_proto_msgTypes,
	}.Build()
	File_examples_balance_balance_proto = out.File
	file_examples_balance_balance_proto_rawDesc = nil
	file_examples_balance_balance_proto_goTypes = nil
	file_examples_balance_balance_proto_depIdxs = nil
}
